services:
  postgresql:
    container_name: container_blogging_api_db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin-api
      - POSTGRES_DB=blogging-api-db
      - POSTGRES_PASSWORD=admin-api
    ports:
      - "5434:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgresql:
    driver: local